//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrador_1.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CLINICA : DbContext
    {
        public CLINICA()
            : base("name=CLINICA")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BARRIOS> BARRIOS { get; set; }
        public virtual DbSet<DIAGNOSTICOS> DIAGNOSTICOS { get; set; }
        public virtual DbSet<EMPLEADOS> EMPLEADOS { get; set; }
        public virtual DbSet<ESPECIALIDADES> ESPECIALIDADES { get; set; }
        public virtual DbSet<HISTORIAS_CLINICAS> HISTORIAS_CLINICAS { get; set; }
        public virtual DbSet<LOCALIDADES> LOCALIDADES { get; set; }
        public virtual DbSet<MEDICOS> MEDICOS { get; set; }
        public virtual DbSet<OBRAS_SOCIALES> OBRAS_SOCIALES { get; set; }
        public virtual DbSet<PACIENTES> PACIENTES { get; set; }
        public virtual DbSet<PLANES> PLANES { get; set; }
        public virtual DbSet<PLANES_OBRA_SOCIAL> PLANES_OBRA_SOCIAL { get; set; }
        public virtual DbSet<PROCEDIMIENTOS> PROCEDIMIENTOS { get; set; }
        public virtual DbSet<PROVINCIAS> PROVINCIAS { get; set; }
        public virtual DbSet<ROLES_USUARIOS> ROLES_USUARIOS { get; set; }
        public virtual DbSet<TIPOS_DOC> TIPOS_DOC { get; set; }
        public virtual DbSet<TIPOS_USUARIO> TIPOS_USUARIO { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
        public virtual DbSet<GENEROS> GENEROS { get; set; }

   
   }


}
