//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrador_1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIAGNOSTICOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIAGNOSTICOS()
        {
            this.PROCEDIMIENTOS = new HashSet<PROCEDIMIENTOS>();
        }
    
        public int tipo_dx { get; set; }
        public string nom_diagnostico { get; set; }
        public Nullable<int> id_especialidad { get; set; }
        public Nullable<bool> alta_complejidad { get; set; }
    
        public virtual ESPECIALIDADES ESPECIALIDADES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROCEDIMIENTOS> PROCEDIMIENTOS { get; set; }
    }
}
