//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrador_1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADOS()
        {
            this.USUARIOS = new HashSet<USUARIOS>();
        }
    
        public int id_empleado { get; set; }
        public string nombre_empleado { get; set; }
        public string apellido_empleado { get; set; }
        public Nullable<int> tipo_doc { get; set; }
        public Nullable<long> nro_doc { get; set; }
        public string calle { get; set; }
        public Nullable<int> nro_dom { get; set; }
        public string email { get; set; }
        public Nullable<long> telefono { get; set; }
        public Nullable<int> id_barrio { get; set; }
    
        public virtual BARRIOS BARRIOS { get; set; }
        public virtual TIPOS_DOC TIPOS_DOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
    }
}
