//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrador_1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANES_OBRA_SOCIAL
    {
        public int id_plan { get; set; }
        public int id_obra_social { get; set; }
        public string nom_plan { get; set; }
    
        public virtual OBRAS_SOCIALES OBRAS_SOCIALES { get; set; }
        public virtual PLANES PLANES { get; set; }
    }
}
