//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrador_1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCEDIMIENTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROCEDIMIENTOS()
        {
            this.HISTORIAS_CLINICAS = new HashSet<HISTORIAS_CLINICAS>();
        }
    
        public int id_procedimiento { get; set; }
        public Nullable<int> tipo_dx { get; set; }
        public Nullable<int> id_medico { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
    
        public virtual DIAGNOSTICOS DIAGNOSTICOS { get; set; }
        public virtual MEDICOS MEDICOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIAS_CLINICAS> HISTORIAS_CLINICAS { get; set; }
    }
}
