//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrador_1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLES_USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROLES_USUARIOS()
        {
            this.TIPOS_USUARIO = new HashSet<TIPOS_USUARIO>();
        }
    
        public string cod_rol { get; set; }
        public string desc_rol { get; set; }
        public Nullable<bool> es_sysadmin { get; set; }
        public Nullable<bool> es_medico { get; set; }
        public Nullable<bool> asigna_turnos { get; set; }
        public Nullable<bool> es_administrativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPOS_USUARIO> TIPOS_USUARIO { get; set; }
    }
}
