//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrador_1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIOS()
        {
            this.MEDICOS = new HashSet<MEDICOS>();
        }
    
        public int id_usuario { get; set; }
        public string nombre_usuario { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<int> id_tipo_usuario { get; set; }
        public string contrasena { get; set; }
    
        public virtual EMPLEADOS EMPLEADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICOS> MEDICOS { get; set; }
        public virtual TIPOS_USUARIO TIPOS_USUARIO { get; set; }
    }
}
